/// Flutter icons Memow
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Memow
///      fonts:
///       - asset: fonts/Memow.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Memow {
  Memow._();

  static const _kFontFam = 'Memow';
  static const _kFontPkg = null;

  static const IconData caw_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caw_2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
